FROM node:18 AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --no-optional --silent
COPY . .
ARG VITE_API_URL='/api'
ENV VITE_API_URL=${VITE_API_URL}
RUN npm run build

FROM caddy:2
COPY --from=builder /app/dist /usr/share/caddy
COPY Caddyfile /etc/caddy/Caddyfile
EXPOSE 80 443
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
